const lw = [
    {
        id: 1,
        name: "Neymar",
        janame: "ネイマール",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/68290-1669394812.jpg?lm=1",
        lw: 5,
        cf: 4,
        rw: 3,
        li: 3,
        pv: 0,
        ri: 2,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 2,
        name: "Hazard",
        janame: "アザール",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/50202-1665067742.jpg?lm=1",
        lw: 4,
        cf: 5,
        rw: 3,
        li: 4,
        pv: 0,
        ri: 2,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 3,
        name: "Vinicius",
        janame: "ヴィニシウス",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/371998-1664869583.jpg?lm=1",
        lw: 5,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 4,
        name: "Grealish",
        janame: "グリーリッシュ",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/203460-1676499047.jpg?lm=1",
        lw: 5,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 5,
        name: "Kvaratskhelia",
        janame: "クヴァラツェリア",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/502670-1663578995.jpg?lm=1",
        lw: 5,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 6,
        name: "Rashford",
        janame: "ラッシュフォード",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/258923-1674473054.jpg?lm=1",
        lw: 5,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 7,
        name: "Martinelli",
        janame: "マルティネッリ",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/655488-1682689091.jpg?lm=1",
        lw: 5,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 8,
        name: "Son",
        janame: "ソン",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/91845-1669336455.jpg?lm=1",
        lw: 5,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 8,
        name: "Saint Maximin",
        janame: "サンマクシマン",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/272642-1557495119.png?lm=1",
        lw: 5,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 9,
        name: "Fati",
        janame: "ファティ",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/466810-1669017589.jpg?lm=1",
        lw: 5,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 10,
        name: "Mitoma",
        janame: "三笘",
        position: "LW",
        positionId: "lw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/504849-1642264453.jpg?lm=1",
        lw: 5,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
]

const cf =[
    {
        id: 1,
        name: "Suarez",
        janame: "スアレス",
        position: "CF",
        positionId: "cf",
        photo: "https://img.a.transfermarkt.technology/portrait/header/44352-1668156555.jpg?lm=1",
        lw: 3,
        cf: 5,
        rw: 3,
        li: 1,
        pv: 0,
        ri: 1,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
    {
        id: 2,
        name: "Lewandowski",
        janame: "レヴァンドフスキ",
        position: "CF",
        positionId: "cf",
        photo: "https://img.a.transfermarkt.technology/portrait/header/38253-1642434304.jpg?lm=1",
        lw: 3,
        cf: 5,
        rw: 3,
        li: 1,
        pv: 0,
        ri: 1,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    },
]

const rw = [
    {
        id: 1,
        name: "Messi",
        janame: "メッシ",
        position: "RW",
        positionId: "rw",
        photo: "https://img.a.transfermarkt.technology/portrait/header/28003-1671435885.jpg?lm=1",
        lw: 1,
        cf: 4,
        rw: 4,
        li: 1,
        pv: 0,
        ri: 5,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 0,
    }
]

const li = [
    {
        id: 1,
        name: "Iniesta",
        janame: "イニエスタ",
        position: "MF",
        positionId: "li",
        photo: "https://img.a.transfermarkt.technology/portrait/header/7600-1685447666.jpg?lm=1",
        lw: 3,
        cf: 0,
        rw: 0,
        li: 5,
        pv: 0,
        ri: 0,
        lb: 3,
        lc: 0,
        rc: 0,
        rb: 0,
    }
]

const pv = [
    {
        id: 1,
        name: "Busquets",
        janame: "ブスケツ",
        position: "MF",
        positionId: "pv",
        photo: "https://img.a.transfermarkt.technology/portrait/header/65230-1668168379.jpg?lm=1",
        lw: 0,
        cf: 0,
        rw: 0,
        li: 1,
        pv: 5,
        ri: 1,
        lb: 1,
        lc: 2,
        rc: 2,
        rb: 1,
    }
]

const ri = [
    {
        id: 1,
        name: "Rakitic",
        janame: "ラキティッチ",
        position: "MF",
        positionId: "ri",
        photo: "https://img.a.transfermarkt.technology/portrait/header/32467-1568021662.jpg?lm=1",
        lw: 0,
        cf: 0,
        rw: 0,
        li: 3,
        pv: 4,
        ri: 4,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 5,
    }
]

const lb = [
    {
        id: 1,
        name: "Alba",
        janame: "アルバ",
        position: "LB",
        positionId: "lb",
        photo: "https://img.a.transfermarkt.technology/portrait/header/69751-1684931206.jpg?lm=1",
        lw: 5,
        cf: 0,
        rw: 0,
        li: 1,
        pv: 0,
        ri: 0,
        lb: 4,
        lc: 0,
        rc: 0,
        rb: 0,
    }
]

const lc = [
    {
        id: 1,
        name: "Umtiti",
        janame: "ウムティティ",
        position: "CB",
        positionId: "lc",
        photo: "https://img.a.transfermarkt.technology/portrait/header/126540-1598302607.jpg?lm=1",
        lw: 0,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 5,
        rc: 4,
        rb: 0,
    }
]

const rc = [
    {
        id: 1,
        name: "Pique",
        janame: "ピケ",
        position: "CB",
        positionId: "rc",
        photo: "https://img.a.transfermarkt.technology/portrait/header/18944-1667548226.jpg?lm=1",
        lw: 0,
        cf: 0,
        rw: 0,
        li: 0,
        pv: 0,
        ri: 0,
        lb: 0,
        lc: 4,
        rc: 5,
        rb: 0,
    }
]

const rb = [
    {
        id: 1,
        name: "Roberto",
        janame: "ロベルト",
        position: "RB",
        positionId: "rb",
        photo: "https://img.a.transfermarkt.technology/portrait/header/85370-1662585931.jpg?lm=1",
        lw: 0,
        cf: 0,
        rw: 4,
        li: 1,
        pv: 1,
        ri: 3,
        lb: 0,
        lc: 0,
        rc: 0,
        rb: 4,
    }
]



export {
    lw,
    cf,
    rw,
    li,
    pv,
    ri,
    lb,
    lc,
    rc,
    rb
}